import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Goldman,
  Great_Vibes,
  Vollkorn,
  Oleo_Script,
  Poppins,
} from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import LoadingScreen from "@/components/LoadingScreen";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const goldman = Goldman({
  variable: "--font-goldman",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  subsets: ["latin"],
  weight: ["400"],
});

const vollkorn = Vollkorn({
  variable: "--font-vollkorn",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const oleoScript = Oleo_Script({
  variable: "--font-oleo-script",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${goldman.variable} ${greatVibes.variable} ${vollkorn.variable} ${oleoScript.variable} ${poppins.variable} antialiased`}
      >
        <Provider>
          <LoadingScreen />
          {children}
        </Provider>
      </body>
    </html>
  );
}
